default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1234 # <--- UPDATE THIS LINE
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: my_demo_app_development

test:
  <<: *default
  database: my_demo_app_test

# ... rest of the file